name: CI

on:
  push:
    branches: [master]
    paths:
      - "lambda-appsync/**"
      - "lambda-appsync-proc/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"
  pull_request:
    branches: [master]
    paths:
      - "lambda-appsync/**"
      - "lambda-appsync-proc/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"

env:
  MSRV: "1.82.0"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust ${{ env.MSRV }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.MSRV }}
          components: rustfmt, clippy

      - name: Cargo Format Check
        run: cargo fmt --all -- --check

      - name: Clippy Check
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Doc Check
        run: RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps --document-private-items

      - name: Run Tests
        run: cargo test --all-features

      - name: Build Documentation
        run: cargo doc --no-deps --document-private-items

  stable:
    name: Stable Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check build
        run: cargo check --all-features
